import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';
const here = path.dirname(fileURLToPath(import.meta.url));
const frames = path.resolve(here, '../../776bc/pursuit/assets/frames');
const out = path.join(here, 'assets');
fs.mkdirSync(out, { recursive: true });
const photo = n => `data:image/jpeg;base64,${fs.readFileSync(path.join(frames, `frame_${n}.jpg`)).toString('base64')}`;
const palette = { dark:'#062e30', deep:'#031c1e', mint:'#83ead7', paper:'#f4f1e9', gold:'#b5a06f', muted:'#b4c9c6' };
const common = `<defs><linearGradient id="shade" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#031c1e" stop-opacity="0"/><stop offset="1" stop-color="#031c1e" stop-opacity=".95"/></linearGradient><clipPath id="photo"><rect x="0" y="0" width="1200" height="990"/></clipPath></defs>`;
const footer = `<line x1="70" y1="1410" x2="1130" y2="1410" stroke="${palette.muted}" stroke-opacity=".55"/><text x="70" y="1460" font-family="Ubuntu Sans, sans-serif" font-size="27" font-weight="700" fill="${palette.paper}">Optiflows</text><text x="1130" y="1460" text-anchor="end" font-family="Ubuntu Sans, sans-serif" font-size="21" letter-spacing="3" fill="${palette.muted}">776BC / THE PURSUIT</text>`;
const svg = body => `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1500" viewBox="0 0 1200 1500">${common}${body}</svg>`;
const pages = [
  [ 'post-01-source-1200x1500.png', svg(`<rect width="1200" height="1500" fill="${palette.deep}"/><image href="${photo('001')}" x="-720" y="0" width="2640" height="1100" preserveAspectRatio="xMidYMid slice" clip-path="url(#photo)"/><rect width="1200" height="1010" fill="url(#shade)"/><rect x="70" y="70" width="178" height="48" rx="24" fill="${palette.mint}"/><text x="159" y="102" text-anchor="middle" font-family="Ubuntu Sans, sans-serif" font-size="19" font-weight="700" letter-spacing="2" fill="${palette.deep}">CASE STUDY</text><text x="70" y="833" font-family="Ubuntu Sans, sans-serif" font-size="111" font-weight="800" fill="${palette.paper}">One story.</text><text x="70" y="950" font-family="Ubuntu Sans, sans-serif" font-size="111" font-weight="800" fill="${palette.mint}">Several ways in.</text><text x="70" y="1104" font-family="Ubuntu Sans, sans-serif" font-size="34" fill="${palette.paper}">A 776BC Pursuit story, carried across formats.</text><text x="70" y="1263" font-family="Ubuntu Sans, sans-serif" font-size="22" letter-spacing="4" fill="${palette.gold}">SOURCE / STORY / EDITORIAL SYSTEM</text>${footer}`) ],
  [ 'post-02-extensions-1200x1500.png', svg(`<rect width="1200" height="1500" fill="${palette.paper}"/><rect width="1200" height="242" fill="${palette.deep}"/><text x="70" y="106" font-family="Ubuntu Sans, sans-serif" font-size="26" font-weight="700" letter-spacing="3" fill="${palette.mint}">776BC / THE PURSUIT</text><text x="70" y="199" font-family="Ubuntu Sans, sans-serif" font-size="78" font-weight="800" fill="${palette.paper}">Different formats.</text><text x="70" y="324" font-family="Ubuntu Sans, sans-serif" font-size="70" font-weight="800" fill="${palette.deep}">The same idea.</text><rect x="70" y="378" width="1060" height="412" fill="${palette.dark}"/><image href="${photo('002')}" x="70" y="378" width="625" height="412" preserveAspectRatio="xMidYMid slice"/><text x="738" y="438" font-family="Ubuntu Sans, sans-serif" font-size="23" letter-spacing="3" fill="${palette.gold}">PULL QUOTE</text><text x="738" y="509" font-family="Ubuntu Sans, sans-serif" font-size="35" font-weight="700" fill="${palette.paper}">“My back faces</text><text x="738" y="558" font-family="Ubuntu Sans, sans-serif" font-size="35" font-weight="700" fill="${palette.paper}">the finish line.</text><text x="738" y="625" font-family="Ubuntu Sans, sans-serif" font-size="31" fill="${palette.paper}">I pursue something</text><text x="738" y="672" font-family="Ubuntu Sans, sans-serif" font-size="31" fill="${palette.paper}">I can’t see.”</text><rect x="70" y="815" width="650" height="465" fill="#fff"/><text x="105" y="870" font-family="Ubuntu Sans, sans-serif" font-size="23" letter-spacing="3" fill="${palette.dark}">LONG READ</text><text x="105" y="951" font-family="Ubuntu Sans, sans-serif" font-size="50" font-weight="800" fill="${palette.deep}">Racing the line</text><text x="105" y="1011" font-family="Ubuntu Sans, sans-serif" font-size="50" font-weight="800" fill="${palette.deep}">you cannot see.</text><text x="105" y="1082" font-family="Ubuntu Sans, sans-serif" font-size="25" fill="${palette.dark}">In rowing, you never see the finish</text><text x="105" y="1120" font-family="Ubuntu Sans, sans-serif" font-size="25" fill="${palette.dark}">line approach. You feel it through the</text><text x="105" y="1158" font-family="Ubuntu Sans, sans-serif" font-size="25" fill="${palette.dark}">bodies ahead of you...</text><text x="105" y="1241" font-family="Ubuntu Sans, sans-serif" font-size="17" fill="${palette.dark}">Excerpt from the Pursuit page</text><rect x="746" y="815" width="384" height="465" fill="${palette.deep}"/><image href="${photo('035')}" x="746" y="815" width="384" height="305" preserveAspectRatio="xMidYMid slice"/><text x="779" y="1175" font-family="Ubuntu Sans, sans-serif" font-size="24" letter-spacing="2" fill="${palette.mint}">SELECTED STILLS</text><text x="779" y="1223" font-family="Ubuntu Sans, sans-serif" font-size="23" fill="${palette.paper}">The visual world continues.</text><rect y="1360" width="1200" height="140" fill="${palette.deep}"/>${footer}`) ],
  [ 'post-03-method-1200x1500.png', svg(`<rect width="1200" height="1500" fill="${palette.deep}"/><text x="70" y="120" font-family="Ubuntu Sans, sans-serif" font-size="25" letter-spacing="4" fill="${palette.mint}">THE OPERATING MODEL</text><text x="70" y="243" font-family="Ubuntu Sans, sans-serif" font-size="86" font-weight="800" fill="${palette.paper}">The system is</text><text x="70" y="343" font-family="Ubuntu Sans, sans-serif" font-size="86" font-weight="800" fill="${palette.mint}">in the decisions.</text><image href="${photo('001')}" x="70" y="432" width="1060" height="384" preserveAspectRatio="xMidYMid slice"/><rect x="70" y="432" width="1060" height="384" fill="${palette.deep}" opacity=".19"/><line x1="70" y1="890" x2="1130" y2="890" stroke="${palette.mint}" stroke-opacity=".55"/><text x="70" y="961" font-family="Ubuntu Sans, sans-serif" font-size="32" font-weight="700" fill="${palette.paper}">Source story</text><text x="70" y="1010" font-family="Ubuntu Sans, sans-serif" font-size="22" fill="${palette.muted}">Choose the idea worth carrying.</text><text x="70" y="1092" font-family="Ubuntu Sans, sans-serif" font-size="32" font-weight="700" fill="${palette.paper}">Useful versions</text><text x="70" y="1141" font-family="Ubuntu Sans, sans-serif" font-size="22" fill="${palette.muted}">Draft for a real audience moment.</text><text x="672" y="961" font-family="Ubuntu Sans, sans-serif" font-size="32" font-weight="700" fill="${palette.paper}">Editorial review</text><text x="672" y="1010" font-family="Ubuntu Sans, sans-serif" font-size="22" fill="${palette.muted}">Check meaning, context and brand.</text><text x="672" y="1092" font-family="Ubuntu Sans, sans-serif" font-size="32" font-weight="700" fill="${palette.paper}">Approved distribution</text><text x="672" y="1141" font-family="Ubuntu Sans, sans-serif" font-size="22" fill="${palette.muted}">Release only what is ready.</text><text x="70" y="1308" font-family="Ubuntu Sans, sans-serif" font-size="27" fill="${palette.gold}">Human judgment stays in the loop.</text>${footer}`) ]
];
for (const [name, content] of pages) {
  const rendered = new Resvg(content, {fitTo:{mode:'width',value:1200}}).render();
  fs.writeFileSync(path.join(out,name), rendered.asPng());
  console.log(name);
}
